name: Auto Blog Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Blog
        run: |
          mkdir -p blog/test-blog
          echo "<h1>It Works</h1>" > blog/test-blog/index.html

      - name: Commit & Push
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "auto@bot.com"
          git add .
          git commit -m "Test blog" || echo "No changes"
          git push
